FROM openjdk:17-jdk-slim
COPY target/spring-skillbox-practice2-0.0.1-SNAPSHOT.jar spring-skillbox-practice2-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/spring-skillbox-practice2-0.0.1-SNAPSHOT.jar"]